### PR TITLE
Gencode exon adapter

### PR DESCRIPTION
**Pull request by dawit-melka**
- Implemented GencodeExonAdapter to process Gencode dataset file and extract exon information for the knowledge graph.

### CODE REVIEW

**Comment by Habush** [comment]
Hi Dawit, thanks for the PR. Can you include the sample file used in the `samples` directory and also make relevant changes to `adapters_config.yaml` not just the `adapters_config_sample.yaml` file?

**Comment by dawit-melka** [comment]
> Hi Dawit, thanks for the PR. Can you include the sample file used in the `samples` directory and also make relevant changes to `adapters_config.yaml` not just the `adapters_config_sample.yaml` file?

Hi Abdulrahman, thank you for the feedback. For this adapter the sample file already exists `gencode_sample.gtf.gz`. I have updated the `adapters_config.yaml`.

**Comment by Habush** [comment]
can you update the path following the similar path as the one that exists for the other adapters?  That is, using the same directory structure as the path for the other adapters

**Comment by dawit-melka** [comment]
> can you update the path following the similar path as the one that exists for the other adapters? That is, using the same directory structure as the path for the other adapters

Path updated following consistent structure.

**Pull request merged**
