### PR TITLE
implement encode ccre adapter

### PR DESCRIPTION
**Pull request by kedistS**
I implement enhancer CCRE adapter.

### CODE REVIEW

**Comment by Habush** [comment]
Hi @kedistS, thanks for the PR! Can you include the first few lines of the file you're importing as a comment on the adapter class. This helps us quickly see the structure of the original file. Please check the existing adapters and also @dawit-melka's PRs.

**Comment by kedistS** [comment]
I added them please take a look at it.

Thank you.

**Comment by Habush** [comment]
The source url is missing. Please check.

**Comment by kedistS** [comment]
I created new PR for this enhancer ccre adapter due to some conflicts so I am going to close this PR.

**Pull request closed without merging**
